version: "3.9"

services: 
  lpslam:
    image: jcslam:dev 
    stdin_open: true
    tty: true
    privileged: true
    network_mode: "host"
    hostname: 'docker-developer'
    command: -c "/bin/zsh -l" 
    volumes:
      - ~/.zsh_history:/home/dockerdev/.zsh_history
      - ~/.ssh:/home/dockerdev/.ssh
      - ~/.vim:/home/dockerdev/.vim
      - ~/.vimrc:/home/dockerdev/.vimrc
      - ~/.config/nvim:/home/dockerdev/.config/nvim
